# taskflow/storage.py
import json
from pathlib import Path
from taskflow.models import Task

# ── Constantes ────────────────────────────────────────────────────────────────

RUTA_PREDETERMINADA   = Path("tasks.json")
ENCODING_LECTURA      = "utf-8-sig"  # utf-8-sig tolerates Windows BOM generated by PowerShell
ENCODING_ESCRITURA    = "utf-8"
INDENTACION_JSON      = 2


# ── Funciones públicas ────────────────────────────────────────────────────────

def load_tasks(ruta_archivo: Path = RUTA_PREDETERMINADA) -> list[Task]:
    """Carga las tareas desde un archivo JSON.

    Si el archivo no existe o está vacío, retorna una lista vacía sin lanzar error.

    Args:
        ruta_archivo: ruta al archivo JSON. Por defecto 'tasks.json'.

    Returns:
        Lista de Task. Vacía si el archivo no existe o está vacío.

    Raises:
        json.JSONDecodeError: si el archivo existe pero contiene JSON malformado.
    """
    if not ruta_archivo.exists():
        return []

    contenido_crudo = ruta_archivo.read_text(encoding=ENCODING_LECTURA).strip()

    if not contenido_crudo:
        return []

    datos_json = json.loads(contenido_crudo)

    return [Task.from_dict(datos_tarea) for datos_tarea in datos_json]


def save_tasks(lista_tareas: list[Task], ruta_archivo: Path = RUTA_PREDETERMINADA) -> None:
    """Guarda la lista de tareas en un archivo JSON.

    Crea el archivo y las carpetas intermedias si no existen.
    Sobreescribe el contenido si el archivo ya existe.

    Args:
        lista_tareas: lista de Task a guardar.
        ruta_archivo: ruta al archivo JSON. Por defecto 'tasks.json'.
    """
    ruta_archivo.parent.mkdir(parents=True, exist_ok=True)

    tareas_serializadas = [tarea.to_dict() for tarea in lista_tareas]

    with open(ruta_archivo, "w", encoding=ENCODING_ESCRITURA) as archivo_destino:
        json.dump(tareas_serializadas, archivo_destino, indent=INDENTACION_JSON, ensure_ascii=False)